--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImJustNozell/YamlSymfony
build-by-default: true
branches:
- main
projects:
  YamlSymfony:
    path: ""
    model: virion
    type: library
...
